version: 0.2

env:
  variables:
    ENV: "dev"

phases:
  install:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - docker build -t codebuild-demo .
      - docker tag codebuild-demo:latest 600902720163.dkr.ecr.eu-west-1.amazonaws.com/codebuild-demo:latest
      - docker push 600902720163.dkr.ecr.eu-west-1.amazonaws.com/codebuild-demo:latest
  post_build:
    commands:
      - echo "post_build"

